http://www.plantuml.com/plantuml/uml/hPJ1Q_904CNl-rSidlGWteKMQwt5Z_9fczx3r9t2qcGtdLq5__kEkqWIDm497ZFxvZVl1MOMpWFvGra8s7jBSatM-1UZHCLblTSL62-pGfUjmfOKadjcATcYGEfu_C3AEit8K-jnbEVp8CZpaGGNnKA1XozmA5TB8IuMvFGnJ9PpkTjcdt86bPxP03-RrKVm6Aq55QklRN5dqCi72Kg5rt4ex82WT9CQamHAK8o_3jR0_nwGJaytp6Z-5v40USXgoTZi_IqYpxxblj1eV0tYdyIgQO-Z7w6m8UqV4h4RnVOBS7vZ719_ZYStJQhxs_Dk3WMqHbGxg-yVhGKV7h2c38-fq7bjm6jhxfwomHuUiW4Pc34kmRtJXJI3OuMc98yW_9RsY9JkuYlwK6jlT5pdo9e8D4eoeMjl-szFmq8wjV_CSBi23sp4st_Pzl-LTVPBKTTIZMkJyNNQvIoYHTVq-kGIkieQXwd_MXyERsYwtEpkni0K2xPsA8i_

@startuml
actor FrontEnd
participant Slim
participant OrdersController
participant OrdersRepository
participant "__:Order__" as Order
database DB

FrontEnd -> Slim : POST /api/orders
activate Slim
Slim -> OrdersController : order = addOrder(orderParams)
activate OrdersController
OrdersController -> OrdersRepository : order = queryAddOrder(orderParams)
activate OrdersRepository

OrdersRepository -> DB : SQL query add client
activate DB
DB --> OrdersRepository : ok
deactivate DB
OrdersRepository -> DB : clientId = lastInsertId()
activate DB
DB --> OrdersRepository : clientId
deactivate DB
OrdersRepository -> DB : SQL query add carFeedPoint
activate DB
DB --> OrdersRepository : ok
deactivate DB
OrdersRepository -> DB : carFeedPointId = lastInsertId()
activate DB
DB --> OrdersRepository : carFeedPointId
deactivate DB
OrdersRepository -> DB : SQL query add destination
activate DB
DB --> OrdersRepository : ok
deactivate DB
OrdersRepository -> DB : destinationId = lastInsertId()
activate DB
DB --> OrdersRepository : destinationId
deactivate DB
OrdersRepository -> DB : SQL query add order
activate DB
DB --> OrdersRepository : ok
deactivate DB
OrdersRepository -> DB : lastId = lastInsertId()
activate DB
DB --> OrdersRepository : lastId
deactivate DB

ref over OrdersRepository
GetOrder order = queryOrder(lastId)
end ref

OrdersRepository -> OrdersController : order
deactivate OrdersRepository

OrdersController -> Order : data = toJSON
ref over Order
GerOrder data = toJSON()
end ref
Order --> OrdersController : data


OrdersController --> Slim : response
deactivate OrdersController
Slim --> FrontEnd : response
deactivate Slim
@enduml