http://www.plantuml.com/plantuml/uml/RLBBJiD03BpxAto4GzHx3bLv52HKKK7u0PEOij8sktWTfFmzpgEAkkGKxNWy7irabvH4kxC7gZK8FabeTTys40rsjOlKAbRUdQ-0epGiwS6e4hndMHc-Smp9cMGF3IbzKc9yl0Uu7C1YE-fYYS_x3znGT9imRi88spY_KkA9TG9lRY6VBXlBQHF_wLZwE--NlOnZUsRCcDNROMA3FOiLjLaCXLFdDG7u4E8LXfxRatw3y1U6NvR_MTJ2f3pXm1Q3KOSlhFXQYS1iJY4TN58a4Ufd6pcyOYNhhDYE46fugOwlbank9ujtAMpWpoqPU6cq74A8eKqCEvEmV-eF

@startuml
actor FrontEnd
participant Slim
participant OrdersController
participant OrdersRepository
database DB

FrontEnd -> Slim : GET /api/orders
Slim -> OrdersController: getOrders()
OrdersController -> OrdersRepository : queryAllOrders()
OrdersRepository -> DB : SQL query
DB --> OrdersRepository: query results

loop query result length
ref over OrdersRepository
create Order
end ref
end

OrdersRepository --> OrdersController : ordersList array

loop ordersList array length
ref over OrdersController
->Order toJSON()
end ref
end

OrdersController --> Slim : JSON
Slim --> FrontEnd: response
@enduml