http://www.plantuml.com/plantuml/uml/ZL7BJiCm4BplL-mH3i7t7AhoA9LGHGNX1qoo54jkRDORfFmzspXLr3G7Jb5cTsR7C-iabgKxUh2r1CPd3grisWQYmgvsqRQ2bNV72s3F3N5wr5KEtXCl3DyfXkHKieV6YlsqYV3f0U1y08lLe8ibRZSVQ6nq9WnC660Tpw-KU239uCqjpASJOpgD9VvqnFszzpFUjACyDQQRrTikRuF-5WjgenWofSvB0l0Xn0iCFRK7-GQcBmo_nDTPr4nMAEC0nbH4k1rVTHUr1sE0D1rLE7rXmUv2Cke-PxTpIT0ospwxku8N7CwgB5O3X19Uglsh1lO_b_CofdfFCcEd2fxxBq-HnT0cWhLAgEOV

@startuml
actor FrontEnd
participant Slim
participant OrdersController
participant OrdersRepository
database DB

FrontEnd -> Slim : GET /api/orders
Slim -> OrdersController: getOrders()
OrdersController -> OrdersRepository : queryAllOrders()
OrdersRepository -> DB : SQL query
DB --> OrdersRepository: query results

loop query result length
ref over OrdersRepository
create Order

//See GetOrder.puml//
end ref
end

OrdersRepository --> OrdersController : ordersList array

loop ordersList array length
ref over OrdersController
->Order toJSON()

//See GetOrder.puml//
end ref
end

OrdersController --> Slim : JSON
Slim --> FrontEnd: response
@enduml